name: notesapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+4
  google_fonts: ^6.3.0
  image_picker: ^1.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.4.2
  #audioplayers: ^6.5.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appLogo.png"
  ios_icon_settings:
    remove_alpha_ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/notifications/messagenotif.wav
